
add_newline = false
# A minimal left prompt
format = """$directory$character"""
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1500

# [directory.substitutions]
# '~/tests/starship-custom' = 'work-project'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[golang]
format = '[ ](bold cyan)'

[docker_context]
disabled = true

